### ISSUE TITLE
JS output

### ISSUE THREAD

**Issue by daarond** [nire0510/jsoq#1]
I like what you have, but converting from TS to JS may be tedious for some users. It might be good to have an already-converted JS version.

**Comment by nire0510** [comment]
Thanks, @daarond !
There's no need for you to convert this package to *.js, even if your project is not TypeScript based; After you `npm i` this package, you'll find a `lib` directory, in which you'll see the *.js file. Then, you just `const jsoq = require('jsoq');` (or `import`), as you would with any other package.
